### ISSUE TITLE
Image creation

### ISSUE THREAD

**Issue by MagerValp** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#10]
Hi,
  I just started reading the guide and since imaging is my day job I was happy to see that you started with a solid introduction to deploying OS X. However I'd like to propose some changes to the first section:

* It's best to build the image using a full installer of the latest version of OS X downloaded from the App Store (currently 10.10.5 14F27). Do not build a 10.10 14A389 image and apply the combo update to it as updates are meant to be installed on live systems and occasionally causes headaches.
* Avoid including extra packages on the image, it'll only make it a pain to maintain and update. Also many packages are badly written and don't install correctly (see https://github.com/MagerValp/AutoDMG/wiki/Packages-Suitable-for-Deployment).
* Rather than installing packages into the image you can include them but install them on first boot, e.g. with Outset: https://github.com/chilcote/outset
* Even better, it's easy to set up Munki for software management, this way you can keep your machines updated too: https://github.com/munki/munki
* If you build your image with AutoDMG a recovery partition should be included in the image and created automatically when you restore with asr. If for some reason it's missing you can create a package that will create it for you (again using the latest OS X installer): https://github.com/MagerValp/Create-Recovery-Partition-Installer

Now on to reading the rest of the guide... :)

**Comment by drduh** [comment]
Hey Per,

That's some good advice, for sure.

I wasn't aware a 10.10.5 build was available in the App Store. Making mention of packages suitable for deployment is definitely a good idea, too. Feel free to PR these changes, or I can make them at a later time. 

However, I am a bit apprehensive about suggesting the use of munki or other system adminstration software. Please correct me if you think I'm wrong, but recommending setting up a software update repository may be beyond the scope and ability of most readers, and may only fatigue and discourage them. This is why I decided to recommend using Homebrew for installing packages and keeping them up to date.

I welcome more of your feedback as you read the rest of the guide! Thank you again.

**Comment by drduh** [comment]
Please have another look, I've updated the instructions for the latest build of Yosemite -- 14F27.

**Comment by TraderStf** [comment]
FYI, but seems you get the guy.
How to Create Recovery Partition in OS X
http://www.hongkiat.com/blog/recovery-partition-os-x/

**Comment by MagerValp** [comment]
Looks good!
