### ISSUE TITLE
Misc. items

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#11]
Hello,
Sorry, don't have time to write it 'correctly' for a merge, I make a copy/paste from my ugly site ;-)

First, may I suggest to add a table of contents/index on top for main subjects.

I have no link with the following, I am using several of them.

Thanks,

Stf

For your VPN chapter and other tools/services you can find very great deal (sometimes free for life) at

<i>Concerning VPN, I have bought 3 for-life deals (ipnator, vpnunlimited and tigervpn), I will try to make a small report about them, how they are on a mac (and android).</i>

StackSocial.com 
Giveaways and deals available for just few days of normally paying software, hardware, tutorials, bundles, gadgets... Some discount are up to 99%, some are free or you give your own price.
Pay attention, some offers can be cheaper on other shopping sites

<i>If you want to thanks me for sparing you hundreds of dollars you can click on my affiliate link
https://stacksocial.com/?rid=1465893
</i>

StartSSL.com 
Free 256-bit SSL Certificate (Class 1) including Web server certificates (SSL/TLS), Client and Email Certificates (S/MIME). 
With a 128 bits and 256 bits encryption, 10000 $USD insurance guaranteed. 
Valid one year and can be renewed for free.

https://www.comodo.com/home/email-security/free-email-certificate.php
Free for personal/home users and 12 USD/year for business users. 
Comodo free email certificate provides digital signature for confidentiality, secure encryption, protect against identity theft, integrates with MS Office and usual applications, trusted by most email clients. 
Check their free products page: antivirus, security tools, total uninstaller, firewall, rescue disk, backup...

SSLlabs.com 
Free online security testing tools: SSL Server Test checks the configuration of SSL web server, SSL Client Test lists all SSL/TLS capabilities of your browser and SSL Fingerprint test.

Abine.com 
Free temporary masked emails. Also encrypted passwords, protect credit card and phone numbers, block hidden trackers, auto-fill, sync...

SpamFence.net 
Free spamfilter services, 99% accuracy and no false-positive!

Objective-see.com
(1. KnockKnock UI - list persistently installed programs to reveal potential malware.)
2. Dylib Hijack Scanner - list apps which can or have been hijacked by malicious dynamic libraries.
3. BlockBlock - prevent installation of any persistent programs without your authorization.

Bleep.pm 
Highly secure, p2p, encrypted and native messaging application.

Fruux.com 
Manage and synchronize contacts, calendars and tasks.
A very good backup.

**Comment by TraderStf** [comment]
For Host file, take a look at https://github.com/2ndalpha/gasmask
I have add several notes and best practices found on the web.
0 instead of 127.0.0.1
Keep the minimum lines: localhost...

Other tools I follow on github about security:
fix-macosx / yosemite-phone-home
fix-macosx / net-monitor
BonzaiThePenguin / Loading
sibiantony / ssleuth
dustinrue / ControlPlane (to automate some tasks, nice to triggers)
ghostwords / chameleon
gorhill / uBlock or chrisaljoudi / uBlock

**Comment by TraderStf** [comment]
For data files, like list of IPs, proxy, IP/Domains blocking lists, secure/filtered DNS servers

http://www.ipdeny.com
http://someonewhocares.org/hosts/

For VPN utilities, not linked to a VPN provider:
Shimo, Viscosity, TunnelBlick, IPSecuritas and (apple network where you can add them manually, switch between them from the menu bar and so get rid of some awful tools used by VPN providers).

To check your VPN, get your IP but also your DNS Server IP: http://whoer.net
To learn DNS: http://www.zytrax.com/books/dns/

Sorry had to go :-/ more later...

**Comment by drduh** [comment]
Whoa @TraderStf - those are some awesome suggestions! I already mention a few, and am familiar with most others. I will have a look at the software or services you've recommended which I haven't seen and definitely include ones I find to be security- and privacy-boosting. You are also welcome to send me a PR with the changes you'd like.

Keep the tips coming!

**Comment by TraderStf** [comment]
a PR ?

forgot this monster data: http://sourceforge.net/projects/adzhosts/

**Comment by TraderStf** [comment]
Thanks, I don't know why I like this subject, security, I do not even need it 😜

Dooo my wife will @@@@ me.

Before I forgot, if one has vpn, ublock, dnscrypt, proxy... set but goes to takes its gmail or similar... you are burned!
Even with few program on your mac which are sending info to get updated... privacy yes... no one really check what is sent.

**Comment by wlad** [comment]
Great resource! How much of it applies as well to El Capitán? (or, in other words, how about starting a guide for El Capitán :) )

**Comment by TraderStf** [comment]
Agree on the idea of ElCap but I always switch to another OS at least 2 months after it's released... new stuff are full of new bugs and gates... hopefully not Bill... Gates 😎

**Comment by drduh** [comment]
I've added a few recommendations. I prefer to shy away from for-profit, commercial services and would rather encourage readers to "DYI" solutions like VPN. Let me know if I missed anything, though.

@wlad I will get working on one when El Cap drops a final build.
