### ISSUE TITLE
Suggest users use the most modern version of gpg

### ISSUE THREAD

**Issue by sg-s** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#13]
Instead of 

```
brew install gpg
```

suggest using 

```
brew install homebrew/versions/gnupg21
```

See [this](https://github.com/sg-s/cryptoparty#gpg) for more details

**Comment by drduh** [comment]
Hey again, @sg-s 

You are right, GnuPG comes in two flavours: 1.4.xx and 2.0.xx. While I think GPG 1.4.xx is sufficient for all functionality described in the guide -- verifying signatures, writing email (I'll add more on this to the guide soon), etc - it's worth mentioning the difference between versions and how to install 2.0.xx should one desire to do so.

Please send me a Pull Request if you have a good idea how to write this information, or I will do it myself later.
