### ISSUE TITLE
2FA - Two-Factor Authentication - Time-based One-Time Password (TOTP)

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#17]
2FA - Two-Factor Authentication for Websites and Mobile Apps

google authenticator and authy
authy is easier and more features, also more simpler when start using a new device!

https://support.google.com/accounts/topic/28786?hl=en
https://en.wikipedia.org/wiki/Google_Authenticator
https://www.authy.com/

**Comment by drduh** [comment]
@TraderStf 2FA is definitely a must for security. But this guide focuses on improving security and privacy in the context of OS X. Which section did you have in mind (maybe a new section?) which would benefit from this recommendation?

**Comment by TraderStf** [comment]
These solutions are free, reliable and simple to set-up.

They provide a higher level of security in a matter of minutes as one of the biggest security hole is the passwords.

This 2FA would be for all third-party services listed, backup, password manager (dashlane...) online access, VPN account, lock-devices remotely (prey, bitdefender...), ISP account, Server Logging...

**Comment by drduh** [comment]
Okay. I will talk about two factor authentication in the Passwords section. It's a good idea, @TraderStf.

**Comment by TraderStf** [comment]
I think that's something most people don't know and are still hurting their mind to manage passwords.
I agree with you, it is no more "local" security, but computers and internet access are almost one these days.
