### ISSUE TITLE
Script?

### ISSUE THREAD

**Issue by prov3it** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#18]
Hello,

Thank you for this guide! I totally understand what I'm doing with this. However i got 2 things. The first is that you actually don't have to download the updates 10.10.4 and 10.10.5 anymore. Apple updated Yosemite to 10.10.5 for download in the app store. 

Now the second one. On the subject Services you wrote a script:
function disable_agent {
  echo "Disabling ${1}"
  launchctl unload -w /System/Library/LaunchAgents/${1}.plist
}

What language is that? is that applescript? because I'm not really much into programming yet and don't know how to run it.

prov3it

**Comment by yb66** [comment]
@prov3it that's shell script. If you open a terminal and run `echo $0` it'll tell you what flavour of shell you're running, which is almost certainly *bash*. If you wanted to use that function repeatedly (which you would, why else declare a function?) then you'd create or open your ~/.bashrc file and paste that in, save it, then run `source ~/.bashrc` to update the shell with the changes. Then you can run the function whenever you open a terminal window.

There are lots of good tutorials on the net for shell scripting.

**Comment by drduh** [comment]
@prov3it Indeed Apple has released a base 10.10.5 image since I wrote this guide. Would you like to give me the build number and cryptographic hashes of the InstallESD image included there? I will definitely add it to the guide.

I believe @yb66 answered your question - it's in fact a small Bash function. I can explain in a little more detail since it's not clear one can copy and paste the "code blocks" into Terminal.

**Comment by prov3it** [comment]
@yb66 thank you for clearing that up!

@drduh sure! I made a bootable installation usb drive for it using:

sudo /Applications/Install\ OS\ X\ Yosemite.app/Contents/Resources/createinstallmedia --volume /Volumes/Yosemite --applicationpath /Applications/Install\ OS\ X\ Yosemite.app --nointeraction

I performed the following command to get the cryptographic hash from the bootable usb drive:
shasum -a256 /Volumes/Install\ OS\ X\ Yosemite/Install\ OS\ X\ Yosemite.app/Contents/SharedSupport/InstallESD.dmg

Output:
24c4934d91401dd2f738c7811d35ae16d3d7993586592a64b9baf625fe0427db  /Volumes/Install OS X Yosemite/Install OS X Yosemite.app/Contents/SharedSupport/InstallESD.dmg

Build:
14F27

**Comment by drduh** [comment]
Can confirm `24c4934d91401dd2f738c7811d35ae16d3d7993586592a64b9baf625fe0427db`, `ef5cc8851b893dbe4bc9a5cf5c648c10450af6bc` and `ff4850735fa0a0a1d706edd21f133ef2`

    $ find "/Volumes/OS X Base System/System" -name "SystemVersion*" -exec defaults read {} \;
    {
      ProductBuildVersion = 14F27;
      ProductCopyright = "1983-2015 Apple Inc.";
      ProductName = "Mac OS X";
      ProductUserVisibleVersion = "10.10.5";
      ProductVersion = "10.10.5";
    }

I'll update the instructions soon.
