### ISSUE TITLE
chromium confusion

### ISSUE THREAD

**Issue by sg-s** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#19]
Hi!

this line:

> Don't use any of those Chromium-derived browsers. They are usually closed source, poorly maintained and make dubious claims to protect your privacy.

seems to contradict your earlier recommendation of Chrome (which is Chromium-derived). Perhaps clarify what you mean by "those Chromium-derived browsers"?

thanks.

**Comment by drduh** [comment]
You're right. I mean closed source derivatives of Chromium such as [SRWare Iron](http://thesimplecomputer.info/the-private-life-of-chromium-browsers) (not trying to pick on it, just one example). Will add this information to the guide, thank you for bringing this up.

**Comment by sg-s** [comment]
thanks for the link -- that was interesting.
