### ISSUE TITLE
OSXAuditor

### ISSUE THREAD

**Issue by zelahi** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#21]
I found another interesting computer forensic tool that could he useful to people.  Its called OSXAuditor and its a great tool to extract information from a mac.  And best of all, its open source!! =)

Here is the github link: https://github.com/jipegit/OSXAuditor

I can do a small write and submit a pull request on it as well

**Comment by drduh** [comment]
Go ahead and PR it to the system monitoring section, if you'd like.
