### ISSUE TITLE
New Section: testing checking tools and services

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#29]
What about adding a new section, testing checking tools and services.

<b>Check Browser Vulnerabilities</b>
https://browsercheck.qualys.com
https://www.browserleaks.com
https://www.browserleaks.com/webrtc
https://www.browserleaks.com/firefox
https://www.poodletest.com - Check if browser is vulnerable due to SSLv3 via block ciphers support.
http://browserspy.dk - Show all the information a browser releases.

<b>Check DNS Leak</b>
https://dnsleaktest.com - Test if your defined DNS servers are leaking information, even when using a secure anonymity or privacy services.

<b>Check Network Vulnerabilities</b>
http://www.speedguide.net/scan.php - Scan Ports for vulnerabilities
http://www.speedguide.net/ports.php - Ports Database of known vulnerabilities
http://www.acunetix.com/free-network-security-scan

<b>Check SSL of a Web Server</b>
https://www.ssllabs.com/ssltest - Deep analysis of the configuration of an SSL web server

<b>Informations</b>
http://whoer.net - Information about the DNS you are using, not just a simple show IP tool.
http://lg.sdv.fr	- IP4/6 Looking Glass and BGP map tools.
http://www.team-cymru.org/IP-ASN-mapping.html - map IP numbers to BGP prefixes and ASN for WHOIS, DNS and HTTP(S).
http://speedtest.net - Test you internet speed, useful to know the impact of using a VPN,...

<b>Device Finger Printing</b>
http://noc.to - Device Finger Printing test and reports. [Source Code](https://github.com/dimalinux/DeviceFingerprint)
https://panopticlick.eff.org - Raw DFP results
https://amiunique.org - Detailed DFP results and ressources.

<b>Anti-Virus Comparatives</b>
http://www.av-comparatives.org
https://www.av-test.org

<b>Miscellaneous</b>
https://geti2p.net - I2P is anonymous overlay network for privacy protection.
https://www.wireshark.org - WireShark is a network protocol analyzer.
https://nmap.org - "Network Mapper" for network discovery and security auditing.
http://sectools.org - Extensive list of 'all' security tools.
https://nordvpn.com/chat - Online secure encrypted chat.
https://nordvpn.com/secret-notes - Create a message that will be destroyed after first reading. 
http://contagiodump.blogspot.be - Collection of latest malware samples, threats, observations and analyses.

**Comment by drduh** [comment]
Those are nice ones and some are already included in the guide. Rather than just have a list of web sites, and in the interest of making the guide approachable to all levels of skill (though obviously tailored for power users), perhaps you could pick a few important sites and ones most relevant to OS X, and include them with a short description of what they're measuring and/or talking about.

**Comment by TraderStf** [comment]
Yes sorry, always in hurry, lack of time :-/
The list is already 'filtered', only the best tools for one purpose, some have of course other tools.
I will try to specify for what in the description.
Thank you for your forgiveness!

**Comment by drduh** [comment]
Go ahead and send a PR when you're ready to add some changes. Thanks!
