### ISSUE TITLE
New Section: Linux Commands

### ISSUE THREAD

**Issue by zelahi** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#32]
So I know this isn't fully just for OS-X but knowing some linux commands I think would be really helpful.  What do you think of adding a small section labeled linux commands and we can add some common ones which would be helpful.  An example is: netstat, or ifconfig/ipconfig

Let me know and I can start working on this and submit a pull request

**Comment by drduh** [comment]
I'm actually hard at work on a similar guide for GNU/Linux now. I'm not sure readers of this OS X guide will find Linux commands all that useful (many may not even have access to a Linux computer). However if you want to add small footnote(s) about the differences in GNU vs BSD utilities such as netstat, that will be good.

**Comment by zelahi** [comment]
O okay, I can add the footnotes.  As for your guide on GNU/Linux please let me know when its up.  I would like to help out as much as I can as. =)

**Comment by drduh** [comment]
For sure. It'll actually be a companion guide to this one teaching how to set up dnscrypt server, Tor bridge, etc. Stay tuned & thanks!

**Comment by drduh** [comment]
Marking this closed for now, but send me a PR anytime you're ready to make some changes.
