### ISSUE TITLE
[Web Browsing] Privacy Tweaks Firefox

### ISSUE THREAD

**Issue by prov3it** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#34]
Hello,

I understand you probuably dont want to add to much information on this subject but maybe something nice to add:
https://github.com/TheCreeper/PrivacyFox

**Comment by drduh** [comment]
That's a nice one to mention. Would you like to send me a pull request?

**Comment by TraderStf** [comment]
Don't know where to put this...

20150930 - On Mac OS X 10.10.5
Vivaldi version 1.0.283.8, not yet on outdated MU... has DNS leak.
Firefox 41 also.
No leak in Safari 9 or Chrome 45.0.2454.101.

See https://ipleak.net/

**Comment by drduh** [comment]
I'm not sure that belongs in the guide - too specific. It is up to the system administrator to be aware of particular things like this. The guide is meant just a general overview.
