### ISSUE TITLE
VPNs

### ISSUE THREAD

**Issue by RSully** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#35]
I've noticed if you use OS X's VPN client (I have not tried openvpn) that if for some reason the VPN disconnects OS X will then start sending traffic over the next interface available. I'm not sure if there are any easy workarounds (I've seen posts where people setup the firewall to drop most traffic on the non-VPN interfaces) or if using openvpn can solve this problem (in which case, perhaps that should be made note of).

**Comment by drduh** [comment]
Check this out -- https://gist.github.com/scy/8122924

**Comment by RSully** [comment]
So openvpn has this problem too, good to know.

That guide is pretty much what I was referencing. Wasn't sure if Apple has done anything more recently to make this easier, but I guess not.
