### ISSUE TITLE
Additional tools and guide

### ISSUE THREAD

**Issue by x44x45x41x4E** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#37]
I could submit a PR for this but I'm not sure where to put them in the guide or how useful they will be over the tools and guides mentioned already so it's up to you to add them. 

[CIRCL automatic launch object detection for Mac OS X](http://www.circl.lu/pub/tr-08/)
[Python script for updating the hosts file](https://github.com/StevenBlack/hosts)
[CIS's Security Benchmark for OS X](https://benchmarks.cisecurity.org/downloads/browse/index.cfm?category=benchmarks.os.unix.osx)

**Comment by TraderStf** [comment]
http://www.controlplaneapp.com
might be also very helpful to help trigger or alert.

FYI, don't know if can be of any interest.
http://superuser.com/questions/811632/prevent-outgoing-traffic-unless-openvpn-connection-is-active-using-pf-conf-on-ma?rq=1

http://superuser.com/questions/577094/how-can-i-tell-if-os-x-is-connected-to-a-vpn-network-from-the-command-line

http://apple.stackexchange.com/questions/46876/how-to-only-route-office-traffic-over-the-vpn-while-having-default-route-for-oth
Switch only in PPTP, not IPSEC...

http://www.sparklabs.com/support/preventing_network_and_dns_traffic_leaks/

http://www.ugdsoft.com/products/vpnwatcher/

http://www.vpntracker.com/us/techdetails.html

**Comment by drduh** [comment]
I wasn't able to locate the open source code for CIRCL. I added a few other ones, though. The rest seemed too esoteric to include, but I may add them as details when expanding sections later. Thanks!

**Comment by operator2010** [comment]
https://prism-break.org/en/

**Comment by TraderStf** [comment]
@operator2010 THANKS !! :+1:
