### ISSUE TITLE
Implementaiton of functions() in "Services"

### ISSUE THREAD

**Issue by BillSantos** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#40]
I really appreciate the work you've done in the Security and Privacy Guide.

I'm interested in how you implement the "Services" section.

Do you incorporate the functions there via a login script (.profile, .bashrc, etc.)

Or do you run them manually?

When I run them manually, I'm required to authenticate some of the services, which would make login script implementation cumbersome.

Just wondering how you do it, and perhaps adding those instructions to the README.MD.

Thanks again for a great guide!

**Comment by drduh** [comment]
Hey there,

Sorry it isn't clear. It is just a bash function with calls to it. You can just copy paste the lines into a Terminal window to run them one by one. I'll try and make that understandable in the guide.
