### ISSUE TITLE
FileVault

### ISSUE THREAD

**Issue by operator2010** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#5]
Protip: Use your Mac a little before turning on the fileVault encription. Install Programms, Setup First and click around to make your system Generated Random key stronger.

**Comment by drduh** [comment]
Hi, @operator2010 

That's an interesting suggestion. Certainly the security of Filevault 2 greatly depends on the security of the pseudo random number generator and entropy it provides. Are you suggesting "using your Mac a little" adds additional entropy to the system?

At least, it's worth having a (sub)section about random number generation. I find some discussion in <https://security.stackexchange.com/questions/42952/how-can-i-measure-and-increase-entropy-on-mac-os-x>

**Comment by drduh** [comment]
I made a mention of this under the Filevault section. Please let me know if you would like to add more information.
